import { createI18n, type Lang } from '@genoffice/i18n'

const strings = {
  zh: {
    title: '自定义 AI 服务',
    serviceTitle: 'AI 服务',
    description: '连接兼容 OpenAI 的接口。密钥仅保存在本机，请求会直接发送到该地址。',
    baseUrl: '服务地址',
    baseUrlHint: '请输入 OpenAI 兼容服务的完整地址，通常以 /v1 结尾。',
    model: '模型',
    modelHint: '输入您要使用的模型名称。',
    apiKey: 'API 密钥（本地服务可不填）',
    apiKeyPlaceholder: '本地服务无需密钥时留空',
    security: '密钥仅保存在本机，不会上传或同步到任何云端。',
    cancel: '取消',
    save: '保存设置',
    saved: '已保存',
    open: '自定义 AI 服务设置',
  },
  en: {
    title: 'Custom AI provider',
    serviceTitle: 'AI service',
    description:
      'Connect an OpenAI-compatible API. The key stays on this device and requests go directly to this endpoint.',
    baseUrl: 'Base URL',
    baseUrlHint: 'Enter the complete OpenAI-compatible endpoint, usually ending in /v1.',
    model: 'Model',
    modelHint: 'Enter the model name you want to use.',
    apiKey: 'API key (optional for local servers)',
    apiKeyPlaceholder: 'Leave empty when the local server does not require one',
    security: 'Your key stays on this device and is never uploaded or synced.',
    cancel: 'Cancel',
    save: 'Save settings',
    saved: 'Saved',
    open: 'Custom AI provider settings',
  },
  ja: {
    title: 'カスタム AI プロバイダー',
    serviceTitle: 'AI サービス',
    description:
      'OpenAI 互換 API に接続します。キーは端末内に保存され、リクエストはこの URL に直接送信されます。',
    baseUrl: 'ベース URL',
    baseUrlHint: 'OpenAI 互換サービスの完全な URL を入力してください。通常は /v1 で終わります。',
    model: 'モデル',
    modelHint: '使用するモデル名を入力してください。',
    apiKey: 'API キー（ローカルサーバーでは任意）',
    apiKeyPlaceholder: '不要な場合は空欄にしてください',
    security: 'キーはこの端末にのみ保存され、アップロードや同期はされません。',
    cancel: 'キャンセル',
    save: '設定を保存',
    saved: '保存済み',
    open: 'カスタム AI プロバイダー設定',
  },
  ko: {
    title: '사용자 지정 AI 공급자',
    serviceTitle: 'AI 서비스',
    description:
      'OpenAI 호환 API에 연결합니다. 키는 이 기기에 저장되며 요청은 이 주소로 직접 전송됩니다.',
    baseUrl: '기본 URL',
    baseUrlHint: 'OpenAI 호환 서비스의 전체 주소를 입력하세요. 일반적으로 /v1로 끝납니다.',
    model: '모델',
    modelHint: '사용할 모델 이름을 입력하세요.',
    apiKey: 'API 키(로컬 서버는 선택 사항)',
    apiKeyPlaceholder: '필요하지 않으면 비워 두세요',
    security: '키는 이 기기에만 저장되며 업로드되거나 동기화되지 않습니다.',
    cancel: '취소',
    save: '설정 저장',
    saved: '저장됨',
    open: '사용자 지정 AI 공급자 설정',
  },
  fr: {
    title: 'Fournisseur IA personnalisé',
    serviceTitle: 'Service IA',
    description:
      'Connecte une API compatible OpenAI. La clé reste sur cet appareil et les requêtes sont envoyées directement à cette adresse.',
    baseUrl: 'URL de base',
    baseUrlHint:
      'Saisissez l’adresse complète du service compatible OpenAI, généralement terminée par /v1.',
    model: 'Modèle',
    modelHint: 'Saisissez le nom du modèle à utiliser.',
    apiKey: 'Clé API (facultative en local)',
    apiKeyPlaceholder: "Laisser vide si elle n'est pas nécessaire",
    security: 'Votre clé reste sur cet appareil et n’est jamais envoyée ni synchronisée.',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saved: 'Enregistré',
    open: 'Paramètres du fournisseur IA personnalisé',
  },
  de: {
    title: 'Benutzerdefinierter KI-Anbieter',
    serviceTitle: 'KI-Dienst',
    description:
      'Verbindet eine OpenAI-kompatible API. Der Schlüssel bleibt auf diesem Gerät; Anfragen gehen direkt an diese Adresse.',
    baseUrl: 'Basis-URL',
    baseUrlHint:
      'Geben Sie die vollständige Adresse des OpenAI-kompatiblen Dienstes ein, meist mit /v1 am Ende.',
    model: 'Modell',
    modelHint: 'Geben Sie den Namen des gewünschten Modells ein.',
    apiKey: 'API-Schlüssel (lokal optional)',
    apiKeyPlaceholder: 'Leer lassen, wenn kein Schlüssel nötig ist',
    security:
      'Ihr Schlüssel bleibt auf diesem Gerät und wird weder hochgeladen noch synchronisiert.',
    cancel: 'Abbrechen',
    save: 'Speichern',
    saved: 'Gespeichert',
    open: 'Einstellungen für benutzerdefinierten KI-Anbieter',
  },
  es: {
    title: 'Proveedor de IA personalizado',
    serviceTitle: 'Servicio de IA',
    description:
      'Conecta una API compatible con OpenAI. La clave permanece en este dispositivo y las solicitudes se envían directamente a esta dirección.',
    baseUrl: 'URL base',
    baseUrlHint:
      'Introduce la dirección completa del servicio compatible con OpenAI, normalmente terminada en /v1.',
    model: 'Modelo',
    modelHint: 'Introduce el nombre del modelo que deseas usar.',
    apiKey: 'Clave API (opcional en servidores locales)',
    apiKeyPlaceholder: 'Déjalo vacío si no se necesita',
    security: 'La clave permanece en este dispositivo y no se carga ni sincroniza.',
    cancel: 'Cancelar',
    save: 'Guardar',
    saved: 'Guardado',
    open: 'Configuración del proveedor de IA personalizado',
  },
  th: {
    title: 'ผู้ให้บริการ AI แบบกำหนดเอง',
    serviceTitle: 'บริการ AI',
    description:
      'เชื่อมต่อ API ที่เข้ากันได้กับ OpenAI คีย์จะเก็บไว้ในอุปกรณ์นี้และส่งคำขอไปยังที่อยู่นี้โดยตรง',
    baseUrl: 'URL หลัก',
    baseUrlHint: 'ป้อนที่อยู่แบบเต็มของบริการที่เข้ากันได้กับ OpenAI ซึ่งโดยทั่วไปจะลงท้ายด้วย /v1',
    model: 'โมเดล',
    modelHint: 'ป้อนชื่อโมเดลที่ต้องการใช้',
    apiKey: 'คีย์ API (ไม่บังคับสำหรับเซิร์ฟเวอร์ภายใน)',
    apiKeyPlaceholder: 'เว้นว่างหากไม่ต้องใช้คีย์',
    security: 'คีย์จะเก็บไว้ในอุปกรณ์นี้เท่านั้น และจะไม่ถูกอัปโหลดหรือซิงค์',
    cancel: 'ยกเลิก',
    save: 'บันทึกการตั้งค่า',
    saved: 'บันทึกแล้ว',
    open: 'การตั้งค่าผู้ให้บริการ AI แบบกำหนดเอง',
  },
  id: {
    title: 'Penyedia AI khusus',
    serviceTitle: 'Layanan AI',
    description:
      'Hubungkan API yang kompatibel dengan OpenAI. Kunci tetap di perangkat ini dan permintaan dikirim langsung ke alamat ini.',
    baseUrl: 'URL dasar',
    baseUrlHint: 'Masukkan alamat lengkap layanan kompatibel OpenAI, biasanya diakhiri /v1.',
    model: 'Model',
    modelHint: 'Masukkan nama model yang ingin digunakan.',
    apiKey: 'Kunci API (opsional untuk server lokal)',
    apiKeyPlaceholder: 'Kosongkan bila tidak diperlukan',
    security: 'Kunci hanya disimpan di perangkat ini dan tidak pernah diunggah atau disinkronkan.',
    cancel: 'Batal',
    save: 'Simpan pengaturan',
    saved: 'Tersimpan',
    open: 'Pengaturan penyedia AI khusus',
  },
  ru: {
    title: 'Пользовательский поставщик ИИ',
    serviceTitle: 'Сервис ИИ',
    description:
      'Подключает API, совместимый с OpenAI. Ключ хранится на этом устройстве, а запросы отправляются прямо на этот адрес.',
    baseUrl: 'Базовый URL',
    baseUrlHint:
      'Введите полный адрес сервиса, совместимого с OpenAI; обычно он заканчивается на /v1.',
    model: 'Модель',
    modelHint: 'Введите название модели.',
    apiKey: 'Ключ API (необязательно для локального сервера)',
    apiKeyPlaceholder: 'Оставьте пустым, если ключ не нужен',
    security: 'Ключ хранится только на этом устройстве и не загружается и не синхронизируется.',
    cancel: 'Отмена',
    save: 'Сохранить',
    saved: 'Сохранено',
    open: 'Настройки пользовательского поставщика ИИ',
  },
  ar: {
    title: 'موفّر ذكاء اصطناعي مخصص',
    serviceTitle: 'خدمة الذكاء الاصطناعي',
    description:
      'الاتصال بواجهة متوافقة مع OpenAI. يُحفظ المفتاح على هذا الجهاز وتُرسل الطلبات مباشرة إلى هذا العنوان.',
    baseUrl: 'عنوان URL الأساسي',
    baseUrlHint: 'أدخل العنوان الكامل للخدمة المتوافقة مع OpenAI، وينتهي عادةً بـ /v1.',
    model: 'النموذج',
    modelHint: 'أدخل اسم النموذج الذي تريد استخدامه.',
    apiKey: 'مفتاح API (اختياري للخوادم المحلية)',
    apiKeyPlaceholder: 'اتركه فارغًا إذا لم يكن مطلوبًا',
    security: 'يُحفظ المفتاح على هذا الجهاز فقط ولا يتم رفعه أو مزامنته.',
    cancel: 'إلغاء',
    save: 'حفظ الإعدادات',
    saved: 'تم الحفظ',
    open: 'إعدادات موفّر الذكاء الاصطناعي المخصص',
  },
  pt: {
    title: 'Provedor de IA personalizado',
    serviceTitle: 'Serviço de IA',
    description:
      'Conecta uma API compatível com OpenAI. A chave fica neste dispositivo e as solicitações vão diretamente para este endereço.',
    baseUrl: 'URL base',
    baseUrlHint:
      'Insira o endereço completo do serviço compatível com OpenAI, normalmente terminado em /v1.',
    model: 'Modelo',
    modelHint: 'Insira o nome do modelo que deseja usar.',
    apiKey: 'Chave de API (opcional em servidor local)',
    apiKeyPlaceholder: 'Deixe em branco se não for necessária',
    security: 'A chave fica somente neste dispositivo e nunca é enviada ou sincronizada.',
    cancel: 'Cancelar',
    save: 'Salvar',
    saved: 'Salvo',
    open: 'Configurações do provedor de IA personalizado',
  },
  it: {
    title: 'Provider IA personalizzato',
    serviceTitle: 'Servizio IA',
    description:
      'Collega una API compatibile con OpenAI. La chiave resta su questo dispositivo e le richieste vengono inviate direttamente a questo indirizzo.',
    baseUrl: 'URL di base',
    baseUrlHint:
      'Inserisci l’indirizzo completo del servizio compatibile con OpenAI, in genere terminante con /v1.',
    model: 'Modello',
    modelHint: 'Inserisci il nome del modello da usare.',
    apiKey: 'Chiave API (facoltativa per server locali)',
    apiKeyPlaceholder: 'Lascia vuoto se non è necessaria',
    security: 'La chiave resta solo su questo dispositivo e non viene caricata né sincronizzata.',
    cancel: 'Annulla',
    save: 'Salva',
    saved: 'Salvato',
    open: 'Impostazioni del provider IA personalizzato',
  },
  pl: {
    title: 'Niestandardowy dostawca AI',
    serviceTitle: 'Usługa AI',
    description:
      'Łączy z interfejsem zgodnym z OpenAI. Klucz pozostaje na tym urządzeniu, a żądania trafiają bezpośrednio pod ten adres.',
    baseUrl: 'Bazowy URL',
    baseUrlHint: 'Podaj pełny adres usługi zgodnej z OpenAI, zwykle kończący się na /v1.',
    model: 'Model',
    modelHint: 'Podaj nazwę modelu, którego chcesz użyć.',
    apiKey: 'Klucz API (opcjonalny lokalnie)',
    apiKeyPlaceholder: 'Pozostaw puste, jeśli klucz nie jest wymagany',
    security:
      'Klucz jest przechowywany tylko na tym urządzeniu i nie jest przesyłany ani synchronizowany.',
    cancel: 'Anuluj',
    save: 'Zapisz',
    saved: 'Zapisano',
    open: 'Ustawienia niestandardowego dostawcy AI',
  },
  nl: {
    title: 'Aangepaste AI-provider',
    serviceTitle: 'AI-service',
    description:
      'Verbindt een OpenAI-compatibele API. De sleutel blijft op dit apparaat en verzoeken gaan rechtstreeks naar dit adres.',
    baseUrl: 'Basis-URL',
    baseUrlHint:
      'Voer het volledige adres van de OpenAI-compatibele service in, meestal eindigend op /v1.',
    model: 'Model',
    modelHint: 'Voer de naam in van het model dat je wilt gebruiken.',
    apiKey: 'API-sleutel (optioneel voor lokale servers)',
    apiKeyPlaceholder: 'Laat leeg als geen sleutel nodig is',
    security:
      'De sleutel blijft alleen op dit apparaat en wordt nooit geüpload of gesynchroniseerd.',
    cancel: 'Annuleren',
    save: 'Opslaan',
    saved: 'Opgeslagen',
    open: 'Instellingen voor aangepaste AI-provider',
  },
  ms: {
    title: 'Penyedia AI tersuai',
    serviceTitle: 'Perkhidmatan AI',
    description:
      'Sambungkan API serasi OpenAI. Kunci kekal pada peranti ini dan permintaan dihantar terus ke alamat ini.',
    baseUrl: 'URL asas',
    baseUrlHint: 'Masukkan alamat penuh perkhidmatan serasi OpenAI, biasanya berakhir dengan /v1.',
    model: 'Model',
    modelHint: 'Masukkan nama model yang mahu digunakan.',
    apiKey: 'Kunci API (pilihan untuk pelayan setempat)',
    apiKeyPlaceholder: 'Biarkan kosong jika tidak diperlukan',
    security:
      'Kunci hanya disimpan pada peranti ini dan tidak pernah dimuat naik atau disegerakkan.',
    cancel: 'Batal',
    save: 'Simpan tetapan',
    saved: 'Disimpan',
    open: 'Tetapan penyedia AI tersuai',
  },
  he: {
    title: 'ספק AI מותאם אישית',
    serviceTitle: 'שירות AI',
    description: 'התחברות ל-API תואם OpenAI. המפתח נשמר במכשיר והבקשות נשלחות ישירות לכתובת זו.',
    baseUrl: 'כתובת URL בסיסית',
    baseUrlHint: 'יש להזין את הכתובת המלאה של השירות התואם ל-OpenAI, שבדרך כלל מסתיימת ב-/v1.',
    model: 'מודל',
    modelHint: 'יש להזין את שם המודל הרצוי.',
    apiKey: 'מפתח API (אופציונלי לשרת מקומי)',
    apiKeyPlaceholder: 'יש להשאיר ריק אם אין צורך במפתח',
    security: 'המפתח נשמר במכשיר זה בלבד ואינו מועלה או מסונכרן.',
    cancel: 'ביטול',
    save: 'שמירת הגדרות',
    saved: 'נשמר',
    open: 'הגדרות ספק AI מותאם אישית',
  },
  hi: {
    title: 'कस्टम AI प्रदाता',
    serviceTitle: 'AI सेवा',
    description:
      'OpenAI-संगत API से कनेक्ट करें। कुंजी इसी डिवाइस पर रहती है और अनुरोध सीधे इस पते पर भेजे जाते हैं।',
    baseUrl: 'बेस URL',
    baseUrlHint: 'OpenAI-संगत सेवा का पूरा पता दर्ज करें, जो आमतौर पर /v1 पर समाप्त होता है।',
    model: 'मॉडल',
    modelHint: 'उस मॉडल का नाम दर्ज करें जिसका आप उपयोग करना चाहते हैं।',
    apiKey: 'API कुंजी (स्थानीय सर्वर के लिए वैकल्पिक)',
    apiKeyPlaceholder: 'ज़रूरत न हो तो खाली छोड़ें',
    security: 'कुंजी केवल इस डिवाइस पर रहती है और कभी अपलोड या सिंक नहीं की जाती।',
    cancel: 'रद्द करें',
    save: 'सेटिंग सहेजें',
    saved: 'सहेजा गया',
    open: 'कस्टम AI प्रदाता सेटिंग',
  },
  'zh-TW': {
    title: '自訂 AI 服務',
    serviceTitle: 'AI 服務',
    description: '連接相容 OpenAI 的介面。金鑰只會儲存在本機，請求會直接傳送到此位址。',
    baseUrl: '服務位址',
    baseUrlHint: '請輸入 OpenAI 相容服務的完整位址，通常以 /v1 結尾。',
    model: '模型',
    modelHint: '輸入您要使用的模型名稱。',
    apiKey: 'API 金鑰（本機服務可不填）',
    apiKeyPlaceholder: '本機服務不需要金鑰時留空',
    security: '金鑰只會儲存在本機，不會上傳或同步至任何雲端。',
    cancel: '取消',
    save: '儲存設定',
    saved: '已儲存',
    open: '自訂 AI 服務設定',
  },
} as const

const translate = createI18n(strings)

const extraStrings = {
  zh: {
    provider: '大模型服务',
    customProvider: 'OpenAI 兼容接口',
    imageSection: '图片生成',
    imageBaseUrl: '图片服务地址',
    imageModel: '生图模型',
    imageModelHint: '使用 OpenAI-compatible /images/generations 接口。',
    imageApiKey: '图片服务 API 密钥（本地服务可不填）',
    activeProvider: '当前默认',
    setDefault: '设为默认',
    providerSettings: '服务配置',
    customProviderDescription: '连接 OpenAI-compatible 服务或本地模型。',
    imageProviderDescription: '用于演示文稿配图和其他图片生成任务。',
  },
  en: {
    provider: 'LLM provider',
    customProvider: 'OpenAI-compatible endpoint',
    imageSection: 'Image generation',
    imageBaseUrl: 'Image service URL',
    imageModel: 'Image model',
    imageModelHint: 'Uses an OpenAI-compatible /images/generations endpoint.',
    imageApiKey: 'Image API key (optional for local servers)',
    activeProvider: 'Current default',
    setDefault: 'Set as default',
    providerSettings: 'Provider settings',
    customProviderDescription: 'Connect an OpenAI-compatible service or local model.',
    imageProviderDescription: 'Used for presentation artwork and other image generation tasks.',
  },
} as const

type BaseKey = keyof typeof strings.zh
type ExtraKey = keyof typeof extraStrings.zh
export type AiProviderSettingsTextKey = BaseKey | ExtraKey

export function aiProviderSettingsText(lang: Lang, key: AiProviderSettingsTextKey): string {
  if (key in extraStrings.zh) {
    const locale = lang === 'zh' || lang === 'zh-TW' ? extraStrings.zh : extraStrings.en
    return locale[key as ExtraKey]
  }
  return translate(lang, key as BaseKey)
}
